- codecov.yml
- Fix the "404 not found" issue on coverage files on codecov.
- Taking into account feedback https://community.codecov.io/t/missing-information-into-coverage-xml-uploaded-file/1470/8 
- See doc on path fixing: https://docs.codecov.io/docs/fixing-paths
- Tests OK on my forked repo, [example](https://codecov.io/gh/mrobertseidowsky-gpsw/gopro-lib-node.gl/src/46c87cde9c30a0e83aa3d6958ba0ce6f34490e4a/libnodegl/buffer.c)
> ci: fix path for codecov coverage badge service

- libnodegl/doc/libnodegl.md
- libnodegl/node_texture.c
- pynodegl-utils/pynodegl_utils/examples/transforms.py
- pynodegl-utils/pynodegl_utils/toolbox/colors.py
- tests/shape.py
- tests/texture.py
The r32g32b32_sfloat format is not supported on AMD Polaris GPUs with
the Vulkan API.
> tests: use AnimatedVec4 instead of AnimatedVec3 for tests

- libnodegl/glcontext_egl.c
Offscreen rendering relies on framebuffer objects and we should only create an unused pbuffer on context that do not support surfaceless context (to stay compatible with old drivers/devices). Moreover, Mesa 20.1.4 (on Arch Linux) broke pbuffer creation on Intel GPUs.
> glcontext_egl: rely on surfaceless contexts if available for all platforms

- libnodegl/gctx.h
- libnodegl/gctx_gl.c
- libnodegl/hwconv.c
- libnodegl/node_hud.c
- libnodegl/node_text.c
- libnodegl/pass.c
- libnodegl/pass.h
- libnodegl/pipeline.c
- libnodegl/pipeline.h
- libnodegl/pipeline_gl.c
- libnodegl/pipeline_gl.h
Also allows attribute buffers to be set after pipeline creation.
> pipeline: decouples draw/dispatch parameters from the pipeline creation.

- tests/api.py
0.3 * 255 = 76.5, which can round to 0x4C or 0x4D depending on the
implementation. Use the unambigous 0.4 (0x66) instead.
> tests/api: adjust clear color value

- libnodegl/nodes.c
The parameter must be read as a pointer if and only it's a pointer
(which is implied by PARAM_FLAG_NON_NULL).
> nodes: fix parameter overread in check_params_sanity()

- libnodegl/doc/libnodegl.md
- libnodegl/glstate.c
- libnodegl/graphicstate.h
- libnodegl/node_graphicconfig.c
- libnodegl/nodes.specs
- tests/shape.py
Culling can either be unset, none (disabled), front (enabled) or back
(enabled).
> graphicconfig: merge cull_face and cull_face_mode params

- pynodegl-utils/pynodegl_utils/control_widgets.py
- pynodegl-utils/pynodegl_utils/misc.py
In practice this also fixes a regression introduced in
3baf8655446f98f3e9c1ef8cd401b5fdd89fb0cf when using Vector(n=2),
typically in examples.medias:centered_medias, where the Qt widget has
minv and maxv in its kwargs, but they are set to None, so kwargs.get()
doesn't work as expected (no fallback on the default).
> utils: rework control kwargs

- libnodegl/gctx_gl.c
ngli_rendertarget_read_pixels() must not be called with data set to
NULL. This commit fixes a potential crash when node.gl is configured to
render offscreen and no capture_buffer is set.
Fixes a regression introduced by
0be6c0b929dfeade2bca163f36eabe963726b1f4.
> gctx_gl: check capture_buffer before reading pixels

- libnodegl/glcontext_wgl.c
node.gl offscreen rendering relies on FBOs, creating a dedicated pixel
buffer context is not required and superfluous.
> glcontext_wgl: do not create a puffer for offscreen rendering

- tests/refs/rtt_load_attachment.ref
- tests/rtt.mak
- tests/rtt.py
Ensures that when a node rtt draw ends, we restore the previous
rendertarget without discarding its attachments.
> tests/rtt: add rtt_load_attachment test

- libnodegl/doc/libnodegl.md
- libnodegl/features.h
- libnodegl/gctx.c
- libnodegl/gctx.h
- libnodegl/gctx_gl.c
- libnodegl/gctx_gl.h
- libnodegl/gen-gl-wrappers.py
- libnodegl/gldefinitions_data.h
- libnodegl/glfeatures_data.h
- libnodegl/glfunctions.h
- libnodegl/glwrappers.h
- libnodegl/hwconv.c
- libnodegl/node_hud.c
- libnodegl/node_rtt.c
- libnodegl/node_text.c
- libnodegl/nodes.h
- libnodegl/pass.c
- libnodegl/rendertarget.h
- libnodegl/rendertarget_gl.c
- libnodegl/rendertarget_gl.h
- ngl-tools/player.c
- tests/rtt.py
- tests/texture.py
Also moves from ngli_gctx_set_rendertarget() to ngli_gctx_{begin,end}_render_pass().
> rendertarget: add load and store operations

- libnodegl/doc/libnodegl.md
- libnodegl/node_rtt.c
- libnodegl/nodes.specs
This parameter was useful for users relying on the OpenGL backend and
prepared the geometry and uv coordinates to deal with the rendertarget
output being vertically flipped.
Since df18098f01ff9795018b23dfc844225f325db527, we alter the
rendertarget output coordinate matrix for OpenGL offscreen rendering.
Moreover, this parameter won't work as expected with other graphics API.
> rtt: remove vflip parameter

- libnodegl/rendertarget_gl.c
- libnodegl/rendertarget_gl.h
While this won't be an issue with the OpenGL default framebuffer as the
framebuffer value is 0 (glDeleteFramebuffers() silently ignores 0), it
is an issue on the EAGL platform as the default framebuffer is a
framebuffer object managed by glcontext_eagl.m.
Forgotten in 0f799469b069a5d6b90724ae6cb96c02bdb1dc41.
> rendertarget_gl: do not try to delete the default framebuffer

- .github/workflows/ci_win.yml
- README.md
- This PR introduces the CI file for build on Windows (here windows-latest but can be fixed to windows-2019).
- I tested the file on my forked repo, see [build](https://github.com/mrobertseidowsky-gpsw/gopro-lib-node.gl/runs/1298599290?check_suite_focus=true)
- Installation of dependencies takes around 10min and the build takes around 1min.
- The env variable CHERE_INVOKING is necessary to stay in the same repository, if not, the Makefile is not found.
- Don't forget to update your README with a new badge !
> ci: Add Github action workflow ci_win.yml file

- ngl-tools/ngl-desktop.c
This uses the same pattern used in SDL upstream to address the issue.
> tools/desktop: simplify macOS SDL issue workaround

- libnodegl/glincludes.h
Forgotten in b794ab5486b314893117aedaf9e815b0ed9264de.
Fixes build on Android.
> glincludes: add missing GL_COLOR, GL_DEPTH and GL_STENCIL definitions

- pynodegl-utils/pynodegl_utils/tests/__init__.py
- pynodegl-utils/pynodegl_utils/tests/cmp.py
- pynodegl-utils/pynodegl_utils/tests/cmp_cuepoints.py
- pynodegl-utils/pynodegl_utils/tests/cmp_fingerprint.py
- pynodegl-utils/pynodegl_utils/tests/cmp_floats.py
- pynodegl-utils/pynodegl_utils/tests/cmp_resources.py
Signed-off-by: Matthieu Bouron <matthieu.bouron@gmail.com>
Here are the following changes from the original commit:
- misc cosmetics
- os.path import changed to import os.path as op
- removed unnecessary calls to os.path.normpath
- used os.path.join() to build image output filenames (instead of string concatenation)
- removed unnecessary prints
- removed unused debug parameter from _run_test()
- renamed debug, debug_func to dump, func_name
- renamed DEBUG option to TESTS_OPTIONS=dump
- added TESTS_OPTIONS description in usage message
- added dump and func_name parameters to all get_out_data() calls (so it still works when GEN is specified)
> pynodegl: add TEST_OPTIONS=dump to dump tests outputs to the filesystem

- pynodegl-utils/pynodegl_utils/misc.py
os.makedirs() can be called in a race condition scenario, which
typically happens during the tests with parallel jobs. The try..except
makes this code resistant to such a scenario.
> utils/misc: use a try-except form in get_nodegl_tempdir()

- Makefile
Forgotten in 825c7e87dd792be82e4f6077334e7cbb602ee973.
> build: remap DEBUG_{GL,MEM,SCENE} to libnodegl debug_opts

- libnodegl/api.c
- libnodegl/backends/gl/glfeatures_data.h
- libnodegl/backends/gl/rendertarget_gl.c
- libnodegl/feature.h
- libnodegl/nodegl.h.in
- libnodegl/pgcraft.c
- pynodegl-utils/pynodegl_utils/tests/data.py
- tests/texture.py
GL_OES_packed_depth_stencil does not define a single combined attachment
point (GL_DEPTH_STENCIL_ATTACHMENT), thus, we need to attach the texture
to both GL_DEPTH_ATTACHMENT and GL_STENCIL_ATTACHMENT.
> rendertarget_gl: fix depth stencil texture attachment on OpenGLES 2.0

- Makefile
- doc/howto/installation.md
- ngl-tools/ngl-desktop.c
- ngl-tools/ngl-ipc.c
The recv and send functions must only be used on sockets (otherwise they
return ENOTSOCK).
> tools: use read/write instead of recv/send where appropriate

- .gitignore
- Makefile
- external/.gitignore
- external/Makefile
This directory can be shared for other potential external dependencies.
> build: isolate sxplayer download in a dedicated external directory

- Makefile
TARGET_OS needs to be exported so it is always available in external
Makefiles.
Fixes TARGET_OS being uninitialized in external/Makefile when the root
Makefile is called without TARGET_OS specified.
> build: always export TARGET_OS

- libnodegl/utils.c
The Microsoft documentation suggests that Windows.h should be included
instead of Fileapi.h and/or Handleapi.h headers. Windows.h takes care of
including a bunch of core headers for the user (Fileapi.h, Handleapi.h,
Profileapi.h to name a few).
This resolves the following compile error on MSVC:
winnt.h(173,1): fatal error C1189: #error: "No Target Architecture".
> utils: remove unnecessary Fileapi.h and Handleapi.h includes

- libnodegl/backends/gl/gctx_gl.c
- libnodegl/log.h
- libnodegl/node_media.c
__func__ is standardised and is part of C99 whereas __FUNCTION__ is not.
See https://tool.oschina.net/uploads/apidocs/gcc-4.7.1-manual/Function-Names.html.
> internal: use __func__ instead of __FUNCTION__

- libnodegl/pass.c
Texture direct rendering is currently not compatible with image
load/store operations.
Fixes regression introduced by 3b8cb6a20a9b7d504ba2fbf24dd898a85fcc5b75.
> pass: disable direct rendering when using image load/store operations

- libnodegl/pgcraft.c
- libnodegl/pipeline.h
This information will be useful for pipelines in modern backends during
binding.
> pipeline: add stage information to textures and buffers

- libnodegl/android_utils.c
- libnodegl/jni_utils.c
Makes the naming consistent with the rest of the codebase.
> jni: rename clazz to cls

- libnodegl/api.c
- libnodegl/backends/gl/glcontext.c
- libnodegl/backends/gl/glcontext.h
- libnodegl/buffer.c
- libnodegl/deserialize.c
- libnodegl/dot.c
- libnodegl/gctx.c
- libnodegl/gctx.h
- libnodegl/gen_doc.c
- libnodegl/gen_specs.c
- libnodegl/hud.c
- libnodegl/node_animated.c
- libnodegl/node_animkeyframe.c
- libnodegl/node_block.c
- libnodegl/node_buffer.c
- libnodegl/node_rtt.c
- libnodegl/node_texture.c
- libnodegl/node_timerangefilter.c
- libnodegl/nodes.c
- libnodegl/nodes.h
- libnodegl/params.c
- libnodegl/pass.c
- libnodegl/pipeline.c
- libnodegl/program.c
- libnodegl/rendertarget.c
- libnodegl/serialize.c
- libnodegl/texture.c
- libnodegl/transforms.c
We should avoid using C++ keywords, especially in headers, so that
node.gl code can be used from both C and C++
> nodegl: rename class to cls

- ngl-tools/ngl-desktop.c
> ngl-desktop: port temp directory to windows

- pynodegl-utils/pynodegl_utils/tests/__init__.py
Currently, we only have an exit code to indicate if the test passed or failed.  
This makes it more clear to the user if the test passed or failed, especially if running the test manually (not via meson)
> pynodegl-utils: add log messages for test passed / failed

- ngl-tools/ngl-ipc.c
On Windows/MSVC, close() cannot be used on sockets.
This commits prevents ngl-ipc from exiting prematurely (with an error
code different from 0) and allows ngl-ipc to be used by the
pynodegl-utils hooks.
> tools/ipc: use closesocket() instead of close() on Windows

- .github/workflows/ci_coverage.yml
- .github/workflows/ci_linux.yml
- .github/workflows/ci_mingw.yml
- README.md
This speeds up the checkout as it uses git clone --depth 1 by default.
> ci/linux,coverge: use actions/checkout version 2

- Makefile
- pynodegl/setup.py
- tests/meson.build
Invoke windows executables from wsl bash shell directly,
instead of bash invoking command prompt, invoking the windows executable.
This allows us to unify the code across platforms.
> build: misc part 6

- .github/workflows/ci_msvc.yml
- doc/howto/installation.md
56136ffae69a4a7f8b9cd5452713925417d47367 is preceding
f6a877255e8b648eeec18ba6efb015e601f2286f that disabled the shared build
of shaderc.
> ci/doc: update vcpkg commit id to the latest known revision working for shaderc

- .gitignore
- Makefile
Add logic to indicate when prefix target actually completes.
This improves error handling.  Currently make thinks prefix target
is completed when the folder is created.
However, the prefix target may fail after the folder is created.
> build: misc part 3

- .github/workflows/ci_mac.yml
- .github/workflows/ci_mingw.yml
- .github/workflows/ci_msvc.yml
- doc/howto/installation.md
Pip is pulled from within the Python venv, it should not be required on
the host.
> doc,ci: remove unneeded pip requirement

- libnodegl/node_streamedbuffer.c
StreamedBuffer nodes are based on struct buffer_priv not struct
variable_priv.
This was not causing any issue as the size of the varilable_priv
structure (368 bytes) is larger than the size of the buffer_priv one
(200 bytes).
> streamedbuffer: use correct priv_size

- libnodegl/meson.build
Fixes the following compile errors:
undefined reference to 'ngli_mat4_mul_aarch64'
undefined reference to 'ngli_mat4_mul_vec4_aarch64'
> test_asm: fix build on aarch64 systems

- .github/workflows/ci_msvc.yml
- configure.py
Allows the user to specify the meson backend to use (build only).
> build/configure: add build-backend option

- libnodegl/backends/gl/gctx_gl.c
- libnodegl/gpu_capture.h
- libnodegl/gpu_capture_renderdoc.c
This will be useful later on if the capture backend needs to access to
the underlying graphics resources.
> gpu_capture: pass gctx to gpu_capture_create()

- libnodegl/backends/gl/hwupload_videotoolbox_darwin_gl.c
- libnodegl/backends/gl/hwupload_videotoolbox_ios_gl.c
- libnodegl/hwupload.c
- libnodegl/hwupload.h
- libnodegl/node_texture.c
The goal of this PR is to progressively change the API of the hwupload module to move away the API from depending on the internal nodes structures. It also includes a bunch of fixes for the videotoolbox hwupload modules.
> Hwupload improvements - part 1

- libnodegl/src/utils.c
utils: This option under windows enable multi process to read the same file at the same time.
If we do not set this option, 2 or more ngl-desktop process running in parallels could failed to get size of asset.
No side effects.
> utils: add shared read for ngli_get_filesize for Windows

- .github/workflows/ci_msvc.yml
- doc/usr/howto/installation.md
- tests/media.py
tests: build ffmpeg with zlib
tests: test_fingerprint tolerance set to 2 for media_queue because of OpenGLES rendering difference under Windows.
> tests: node.gl windows all the tests are not working

- CHANGELOG.md
- libnodegl/meson.build
- libnodegl/nodegl.rc.in
Add properties informations with a rc file for the dll under Windows
- Copyrights
- Version
- Platform
- Name
It enables user or/and developer or/and tester to report easily the dll version used inside the projet.
It also enables to check if there is some mistake on distributing the dll.
> build: add properties informations with a rc file for the dll under windows
